# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.7.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = ">=2.41.0"
    }
    github = {
      source  = "integrations/github"
      version = "~> 5.0"
    }
  }
}

terraform {
    backend "azurerm" {}
}

provider "azurerm" {
  use_oidc = true
  features {}
  subscription_id = "990e5abb-4d0c-4a4e-9954-f0138b327718"
}
